name: mmdd
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - ffmpeg=4.3
  - filelock=3.4.2
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - h5py=3.6.0
  - hdf5=1.10.6
  - huggingface_hub=0.2.1
  - idna=3.3
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pillow=8.4.0
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.9.0
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - readline=8.1.2
  - regex=2021.11.2
  - requests=2.27.1
  - sacremoses=0.0.43
  - sentencepiece=0.1.95
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - tokenizers=0.10.3
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm=4.62.3
  - transformers=4.14.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.7
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.2.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - audioread==2.1.9
    - cachetools==5.2.0
    - cycler==0.11.0
    - decorator==4.4.2
    - deepctr-torch==0.2.8
    - einops==0.4.1
    - flatbuffers==1.12
    - fonttools==4.34.4
    - fvcore==0.1.5.post20221221
    - gast==0.4.0
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.47.0
    - imageio==2.14.1
    - imageio-ffmpeg==0.4.7
    - imgaug==0.4.0
    - iopath==0.1.10
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - librosa==0.9.2
    - llvmlite==0.39.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - moviepy==1.0.3
    - networkx==2.6.3
    - nltk==3.8.1
    - numba==0.56.0
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - pandas==1.4.3
    - pooch==1.6.0
    - portalocker==2.10.1
    - proglog==0.1.10
    - protobuf==3.19.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-dateutil==2.8.2
    - pytorch-metric-learning==2.0.1
    - pytz==2022.1
    - pywavelets==1.2.0
    - requests-oauthlib==1.3.1
    - resampy==0.4.0
    - rsa==4.9
    - scikit-image==0.19.1
    - scikit-learn==1.1.1
    - scipy==1.7.3
    - shapely==1.8.2
    - sklearn==0.0
    - soundfile==0.10.3.post1
    - tabulate==0.9.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-logger==0.1.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - torchmetrics==0.9.3
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - yacs==0.1.8